[versions]
#agp = "8.13.2"
#kotlin = "2.0.21"
#coreKtx = "1.17.0"
#junit = "4.13.2"
#junitVersion = "1.3.0"
#espressoCore = "3.7.0"
#appcompat = "1.5.1"
#material = "1.10.0"
#legacySupportV4 = "1.0.0"
#navigationFragmentKtx = "2.5.3"
#navigationUiKtx = "2.5.3"
#koin = "3.5.6"
#safeargs = "2.9.3"
#room = "2.6.1"
#ksp = "2.0.21-1.0.27"


agp = "7.4.2"
kotlin = "1.7.22"
coreKtx = "1.9.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
navigationFragmentKtx = "2.5.3"
navigationUiKtx = "2.5.3"
safeargs = "2.5.3"
koin = "3.3.3"
room = "2.4.3"
ksp = "1.7.22-1.0.8"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "safeargs"}
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

